#!/usr/bin/env python
# -*- coding:utf-8 -*-
"""
====================================
@File    :  venue.py
@Time    :  2022/06/28 14:17:01
@Author  :  LiuKeCode@hotmail.com
@Desc    :  None
====================================
"""

# here put the import lib

HEX = "GBBO"
BINANCE = "BINANCE"
BINANCEUS = "BINANCEUS"
COINBASEPRO = "COINBASEPRO"
FTX = "FTX"
HUOBI = "HUOBI"
KUCOIN = "KUCOIN"
OKCOIN = "OKCOIN"
OKX = "OKX"

BITBAY = "BITBAY"
BITHUMB = "BITHUMB"
BITMAX = "BITMAX"
BITSO = "BITSO"
BITSTAMP = "BITSTAMP"
BITTREX = "BITTREX"
BLOCKCHAIN = "BLOCKCHAIN"
COINBASEPROUK = "COINBASEPROUK"
COINONE = "COINONE"
CRYPTO = "CRYPTO"
EXMO = "EXMO"
GATEIO = "GATEIO"
GEMINI = "GEMINI"
INDEPENDENTRESERVE = "INDEPENDENTRESERVE"
INDODAX = "INDODAX"
ITBIT = "ITBIT"
KORBIT = "KORBIT"
KRAKEN = "KRAKEN"
KRAKENUK = "KRAKENUK"
LIQUID = "LIQUID"
UPBIT = "UPBIT"
